name: Apply Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  apply_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Load cached venv
        id: cached-rye-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('.github/dependabot/requirements-dev.txt') }}
      - name: Set up Python 3.11
        if: steps.cached-rye-dependencies.outputs.cache-hit != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: .github/dependabot/requirements-dev.txt
      - name: Install dependencies
        if: steps.cached-rye-dependencies.outputs.cache-hit != 'true'
        run: pip install -r .github/dependabot/requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run
      - name: Auto Commit
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change
      - name: Pytest
        run: pytest -sv tests
